### PR TITLE
Adds config.schema.json file

### PR DESCRIPTION
**Pull request by codyc1515**
Adds support for [plug-in settings GUI](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI)

### CODE REVIEW

**Comment by codyc1515** [comment]
Note: I have not added the MQTT section as I am not 100% sure how to do this. I would imagine if you know enough to set-up MQTT then you probably know how to edit a config file.

**Comment by hannseman** [comment]
Cool, thanks! 

But why remove `config-sample.json`? In my opinon it can be good for beginners to have a complete homebridge config example as a reference. It's also referenced in both `README.md` and `package.json` which will break. If it wasn't removed for a good reason please revert that delete and I'll merge this.

**Comment by codyc1515** [comment]
Sweet, wasn't sure what the feeling was on that. I have added it back now.

**Comment by hannseman** [comment]
Thanks!

**Pull request merged**
