### PR TITLE
Added Node 10 compatibility

### PR DESCRIPTION
**Pull request by GorkaMM**
While official Noble repo adds support for Node 10, there's a fork that solved the compatibly issue published as [@abandonware/noble](https://www.npmjs.com/package/@abandonware/noble).

For this fork I just modified the `package.json` and `scanner.js` files.

I'm currently running it on a Raspberry Pi and it works like a charm.

### CODE REVIEW

**Comment by hannseman** [comment]
Hi! Thanks for the PR. Yes I'm aware of that fork. The reason why I haven't switched is that I wanted to see if the author was interested in also bringing in support for MacOS Mojave as that to is broken, see https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/24.

I've opened the PR https://github.com/abandonware/noble/issues/4 but haven't gotten any response what in almost a month which made me wonder if that fork really is the way to go. But maybe it's better to actually get Node 10 support and then start thinking about MacOS Mojave support. 

The test suite is broken, it is probably caused by proxyquire patching `noble` and not `@abandonware/noble`. Also please remove the version-bump. When bringing in Node 10 support I plan on removing support for any versions older than Node 8 and thus requiring a new major version but for now you can just leave it unchanged.

**Comment by hannseman** [comment]
I've also opened an issue on noble-mac to check if they are interested in depending on the @abandonware-fork. Timeular/noble-mac#23

This would enable us to get support for both Mojave and Node 10 on linux.

**Comment by hannseman** [comment]
Perfect! Could you also run prettier on the code? There's some errors https://travis-ci.org/hannseman/homebridge-mi-hygrothermograph/jobs/484840460#L697

**Comment by GorkaMM** [comment]
Working on it now…

**Comment by hannseman** [comment]
Awesome work! Thank you very much. Lets merge this. I'll make a new release ASAP.

**Pull request merged**
